"""Add relationships to Game, Reviews, and Users

Revision ID: 05a6de7e6033
Revises: 8f9b9a42adc7
Create Date: 2026-01-10 13:42:04.392091

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import app


# revision identifiers, used by Alembic.
revision: str = "05a6de7e6033"
down_revision: Union[str, Sequence[str], None] = "8f9b9a42adc7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("review", "game_id", existing_type=sa.INTEGER(), nullable=True)
    op.create_foreign_key(None, "review", "game", ["game_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "review", type_="foreignkey")
    op.alter_column("review", "game_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
