"""Remove Game summary character limit

Revision ID: 3b135f2b649d
Revises: 9750318537c4
Create Date: 2026-01-09 23:07:03.066743

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "3b135f2b649d"
down_revision: Union[str, Sequence[str], None] = "9750318537c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
