"""Try again to remove character limits with workaround

Revision ID: 8f9b9a42adc7
Revises: b841472dd9c3
Create Date: 2026-01-09 23:16:12.299166

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import app


# revision identifiers, used by Alembic.
revision: str = "8f9b9a42adc7"
down_revision: Union[str, Sequence[str], None] = "b841472dd9c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "game",
        "title",
        existing_type=sa.VARCHAR(length=200),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.alter_column(
        "game",
        "summary",
        existing_type=sa.VARCHAR(length=200),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "game",
        "summary",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.VARCHAR(length=200),
        existing_nullable=True,
    )
    op.alter_column(
        "game",
        "title",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.VARCHAR(length=200),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
