"""Add follow capability

Revision ID: 9bb46b4e25d6
Revises: 8a2cf73ae2b5
Create Date: 2025-12-23 17:40:59.280741

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "9bb46b4e25d6"
down_revision: Union[str, Sequence[str], None] = "8a2cf73ae2b5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "follow",
        sa.Column("followed_id", sa.Integer(), nullable=False),
        sa.Column("follower_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACCEPTED", "PENDING", name="followstatus"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["followed_id"], ["user.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["follower_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("followed_id", "follower_id"),
    )
    op.add_column("user", sa.Column("created_at", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "created_at")
    op.drop_table("follow")
    # ### end Alembic commands ###
