"""Try again to remove character limits

Revision ID: b841472dd9c3
Revises: 3b135f2b649d
Create Date: 2026-01-09 23:14:12.732160

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import app


# revision identifiers, used by Alembic.
revision: str = "b841472dd9c3"
down_revision: Union[str, Sequence[str], None] = "3b135f2b649d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
