"""Change timezone type to aware

Revision ID: c40be542f8ec
Revises: 9bb46b4e25d6
Create Date: 2025-12-23 18:04:08.864282

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "c40be542f8ec"
down_revision: Union[str, Sequence[str], None] = "9bb46b4e25d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
